{% set name = "botocore" %}
{% set version = "1.11.6" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "bd85f6491207b632c76fc6ca3e74b5d75a48c7f06f68ae5e98e794e6be10bc06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10
    - urllib3 >=1.20,<1.24

test:
  imports:
    - botocore
    - botocore.docs
    - botocore.docs.bcdoc
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.chardet
    - botocore.vendored.requests.packages.urllib3
    - botocore.vendored.requests.packages.urllib3.contrib
    - botocore.vendored.requests.packages.urllib3.packages
    - botocore.vendored.requests.packages.urllib3.packages.ssl_match_hostname
    - botocore.vendored.requests.packages.urllib3.util

about:
  home: http://aws.amazon.com/sdk-for-python/
  license_file: LICENSE.txt
  license: Apache 2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  summary: 'Low-level, data-driven core of boto 3.'
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - hajapy
    - tkelman
