{% set name = "botocore" %}
{% set version = "1.10.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "bc1e6c36b1b570462e3b688b3bd3ba662e521cc21ce0a860f85f877179af77c7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<2.7.0
    - docutils >=0.10
    - ordereddict ==1.1  # [py26]
    - simplejson ==3.3.0  # [py26]

test:
  imports:
    - botocore
    - botocore.docs
    - botocore.docs.bcdoc
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.chardet
    - botocore.vendored.requests.packages.urllib3
    - botocore.vendored.requests.packages.urllib3.contrib
    - botocore.vendored.requests.packages.urllib3.packages
    - botocore.vendored.requests.packages.urllib3.packages.ssl_match_hostname
    - botocore.vendored.requests.packages.urllib3.util

about:
  home: https://github.com/boto/botocore
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'Low-level, data-driven core of boto 3.'
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - hajapy
    - tkelman
