{% set version = "1.19.4" %}
{% set hash = "c78fe2fb4790e9f06dc40a28402893f12088c4aa88b739475827d9674972f1c4" %}

package:
  name: botocore
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/botocore/botocore-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - urllib3 >=1.25.4,<1.26

test:
  imports:
    - botocore
    - botocore.docs
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.urllib3

about:
  home: http://aws.amazon.com/sdk-for-python/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  summary: Low-level, data-driven core of boto 3.
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - hajapy
    - tkelman
    - ocefpaf
