{% set version = "1.29.85" %}
{% set hash = "cb7e7e88a09ba807956643849b3a9b4e343a2c117838c0be1ca660052f69bcd2" %}

package:
  name: botocore
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/botocore/botocore-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jmespath >=0.7.1,<2.0.0
    - python-dateutil >=2.1,<3.0.0
    - urllib3 >=1.25.4,<1.27

test:
  imports:
    - botocore
    - botocore.docs
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.urllib3
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://aws.amazon.com/sdk-for-python/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  summary: Low-level, data-driven core of boto 3.
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - hajapy
    - tkelman
    - ocefpaf
