{% set version = "1.34.19" %}
{% set hash = "64352b2f05de5c6ab025c1d5232880c22775356dcc5a53d798a6f65db847e826" %}

package:
  name: botocore
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/botocore/botocore-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - jmespath >=0.7.1,<2.0.0
    - python-dateutil >=2.1,<3.0.0
    - urllib3 >=1.25.4,<1.27
# https://github.com/boto/botocore/pull/3034
#   - urllib3 >=1.25.4,<2.1; python_version>="3.10"

test:
  imports:
    - botocore
    - botocore.docs
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.urllib3
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://aws.amazon.com/sdk-for-python/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  summary: Low-level, data-driven core of boto 3.
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - hajapy
    - tkelman
    - ocefpaf
