{% set version = "1.34.51" %}
{% set hash = "5086217442e67dd9de36ec7e87a0c663f76b7790d5fb6a12de565af95e87e319" %}

package:
  name: botocore
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/botocore/botocore-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  string: pyge38_{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [python_version == "old"]
  string: pyge310_{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [python_version == "new"]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    # selectors break the linter but it's okay in this case
    - python >=3.8  # [python_version == "old"]
    - python >=3.10  # [python_version == "new"]
    - pip
  run:
    - python >=3.8  # [python_version == "old"]
    - python >=3.10  # [python_version == "new"]
    - jmespath >=0.7.1,<2.0.0
    - python-dateutil >=2.1,<3.0.0
    - urllib3 >=1.25.4,<1.27  # [python_version == "old"]
    # https://github.com/boto/botocore/pull/3034
    - urllib3 >=1.25.4,<2.1  # [python_version == "new"]

test:
  imports:
    - botocore
    - botocore.docs
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.urllib3
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://aws.amazon.com/sdk-for-python/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  summary: Low-level, data-driven core of boto 3.
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - hajapy
    - tkelman
    - ocefpaf
