{% set version = "1.35.3" %}
{% set hash = "ff0c3189c0aa588c3aeda3f3e5e37925d64deaac6748310124307f978933e768" %}

package:
  name: botocore
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/botocore/botocore-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  string: pyge38_{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [not python_geq_310]
  string: pyge310_{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [python_geq_310]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8   # [not python_geq_310]
    - python >=3.10  # [python_geq_310]
    - pip
  run:
    - python >=3.8   # [not python_geq_310]
    - python >=3.10  # [python_geq_310]
    - jmespath >=0.7.1,<2.0.0
    - python-dateutil >=2.1,<3.0.0
    # https://github.com/boto/botocore/pull/3034
    - urllib3 >=1.25.4,<1.27       # [not python_geq_310]
    # https://github.com/boto/botocore/pull/3141
    - urllib3 >=1.25.4,!=2.2.0,<3  # [python_geq_310]

test:
  imports:
    - botocore
    - botocore.docs
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.urllib3
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://aws.amazon.com/sdk-for-python/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  summary: Low-level, data-driven core of boto 3.
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - hajapy
    - tkelman
    - ocefpaf
